### ISSUE TITLE
Exception when launching demo

### ISSUE THREAD

**Issue by uzername** [arakis/ProcEngine#3] opened 2020-06-03 12:17 UTC
I have cloned repository using --recursive . Opened solution and built it in Visual Studio. 

When launching and compiling Demo project I get such exception: 

![image](https://user-images.githubusercontent.com/864126/83635494-ffa23580-a5ac-11ea-92c7-225bb11b4e6c.png)

```
SixLabors.ImageSharp.ImageProcessingException
  HResult=0x80131500
  Message=An error occurred when processing the image using DrawTextProcessor`1. See the inner exception for more detail.
  Source=SixLabors.ImageSharp
  StackTrace:
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, TextGraphicsOptions options, String text, Font font, IBrush brush, IPen pen, PointF location)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, TextGraphicsOptions options, String text, Font font, Color color, PointF location)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, String text, Font font, Color color, PointF location)
   at Aximo.Engine.Components.Geometry.StatsComponent.<>c__DisplayClass4_0.<UpdateFrame>b__1(IImageProcessingContext ctx) in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Components\Geometry\StatsComponent.cs:line 42
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)
   at Aximo.Engine.Components.Geometry.StatsComponent.UpdateFrame() in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Components\Geometry\StatsComponent.cs:line 42
   at Aximo.Engine.ActorComponent.UpdateFrameInternal() in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Components\ActorComponent.cs:line 48
   at Aximo.Engine.SceneComponent.UpdateFrameInternal() in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Components\SceneComponent.cs:line 303
   at Aximo.Engine.Actor.UpdateFrameInternal() in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Actors\Actor.cs:line 128
   at Aximo.Engine.SceneContext.OnUpdateFrame() in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\SceneContext.cs:line 133
   at Aximo.Engine.Application.OnUpdateFrameInternal(FrameEventArgs e) in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Application.cs:line 379
   at Aximo.Engine.Application.<RegisterWindowEvents>b__46_1(FrameEventArgs e) in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Application.cs:line 144
   at Aximo.Engine.Windows.WindowContext.OnUpdateFrameInternal(FrameEventArgs e) in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Windows\WindowContext.cs:line 79
   at OpenToolkit.Windowing.Desktop.GameWindow.OnUpdateFrame(FrameEventArgs args)
   at Aximo.Engine.Windows.RenderWindow.OnUpdateFrame(FrameEventArgs e) in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Windows\RenderWindow.cs:line 81
   at OpenToolkit.Windowing.Desktop.GameWindow.DispatchUpdateFrame()
   at OpenToolkit.Windowing.Desktop.GameWindow.Run()
   at Aximo.Engine.Windows.WindowContext.UIThread() in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Windows\WindowContext.cs:line 202
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

  This exception was originally thrown at this call stack:
	SixLabors.ThrowHelper.ThrowArgumentOutOfRangeException(string, string)
	SixLabors.ThrowHelper.ThrowArgumentOutOfRangeExceptionForMustBeGreaterThanOrEqualTo<T>(T, T, string)
	SixLabors.ImageSharp.Memory.MemoryGroup<T>.Allocate(SixLabors.ImageSharp.Memory.MemoryAllocator, long, int, SixLabors.ImageSharp.Memory.AllocationOptions)
	SixLabors.ImageSharp.Memory.MemoryAllocatorExtensions.AllocateGroup<T>(SixLabors.ImageSharp.Memory.MemoryAllocator, long, int, SixLabors.ImageSharp.Memory.AllocationOptions)
	SixLabors.ImageSharp.Memory.MemoryAllocatorExtensions.Allocate2D<T>(SixLabors.ImageSharp.Memory.MemoryAllocator, int, int, SixLabors.ImageSharp.Memory.AllocationOptions)
	SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor<TPixel>.CachingGlyphRenderer.Render(SixLabors.ImageSharp.Drawing.IPath)
	SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor<TPixel>.CachingGlyphRenderer.EndGlyph()
	SixLabors.Fonts.GlyphInstance.RenderTo(SixLabors.Fonts.IGlyphRenderer, float, System.Numerics.Vector2, System.Numerics.Vector2, float)
	SixLabors.Fonts.TextRenderer.RenderText(System.ReadOnlySpan<char>, SixLabors.Fonts.RendererOptions)
	SixLabors.Fonts.TextRenderer.RenderText(string, SixLabors.Fonts.RendererOptions)
    ...
    [Call Stack Truncated]
Inner Exception 1:
ArgumentOutOfRangeException: Parameter "bufferAlignment" (System.Int32) must be greater than or equal to 0, was -2147483643 (Parameter 'bufferAlignment')

```

**Comment by arakis** [comment] 2020-06-08 11:47
How did you checked out the git repository? It seems the Asset ( https://github.com/AximoGames/AxEngine/blob/master/Assets/Textures/woodenbox.png ) is not downloaded. You can download them manually if you do not have git LFS ( https://git-lfs.github.com/ )

In the next days, I will completely remove the LFS-Objects / not using git LFS anymore, because of exactly that situation.

**Comment by arakis** [comment] 2020-06-08 11:53
Hm, but if I look closer at your stack trace, it seems it may have another reason. It seems the "Image"-Object is not initialized correctly. I will try to reproduce this today.  I never saw this before. Maybe you can uncomment the line https://github.com/AximoGames/AxEngine/blob/master/Demo/DemoApplication.cs#L178 just for testing.

**Comment by arakis** [comment] 2020-06-08 18:24
I was not able to reproduce this issue. Any hints or further debugging would be great. In the meantime, I opened an issue here: https://github.com/SixLabors/ImageSharp/issues/1218

**Comment by JimBobSquarePants** [comment] 2020-06-09 14:56
@uzername Is this issue replicable every time you start the demo application?

If so can you please update the reference to ImageSharp.Drawing to  [1.0.0-beta0009](https://www.nuget.org/packages/SixLabors.ImageSharp.Drawing/1.0.0-beta0009) and let us know if the issue is still present. The value passed to the allocator is dependent on the bounds of a given path so it could be the case that those bounds are incorrectly calculated. We've recently some some work to clean up bounds calculation.

**Comment by LevYas** [comment] 2020-07-04 11:37
I have an exception too, but I'm not sure is the reason the same or not.
After the checkout I run `git-lfs pull` and it downloaded png's.
Console log:
```
[14:29:39.163 VRB] <Startup`1> 64 Bit System detected. (Pointer Size: 8 Bytes)
[14:29:39.204 VRB] <Startup`1> OS: Microsoft Windows NT 6.2.9200.0
[14:29:39.207 VRB] <Startup`1> Configure for console session
[14:29:39.237 INF] <DebugHelper> Thread #6 Update Thread
[14:29:39.265 INF] <Application> Init Glfw
[14:29:39.361 INF] <Application> GLFW Version: 3.3.0 Win32 WGL EGL OSMesa VisualC DLL
[14:29:39.363 INF] <Application> Create Window
[14:29:39.556 VRB] <RenderWindow> Created window
[14:29:39.575 VRB] <Application> Init OpenGL Bindings
[14:29:39.577 VRB] <Application> Grab Context
[14:29:39.580 VRB] <Application> Load OpenGL Bindings
[14:29:39.582 INF] <Application> Vendor: Intel, version: 3.3.0 - Build 10.18.10.5059, shadinglangVersion: 3.30 - Build 10.18.10.5059, renderer: Intel(R) HD Graphics 4000
[14:29:39.659 INF] <Texture> Loading: Textures/woodenbox.png
[14:29:39.847 INF] <Texture> Loading: Textures/woodenbox_specular.png
[14:29:39.866 INF] <Texture> Loading: Textures/wood.png
[14:29:40.835 VRB] <Application> Update Frame #0
[14:29:40.841 VRB] <RendererTexture> Alloc Texture #1 Color/White
[14:29:40.852 VRB] <RendererTexture> Alloc Texture #2 Color/Black
[14:29:40.854 VRB] <RendererTexture> Alloc Texture #3 Color/Gray
[14:29:40.856 VRB] <RendererTexture> Alloc Texture #4 Color/Red
[14:29:40.857 VRB] <RendererTexture> Alloc Texture #5 Color/Green
[14:29:40.859 VRB] <RendererTexture> Alloc Texture #6 Color/Blue
[14:29:40.866 VRB] <RendererTexture> Alloc Texture #7 Forward
[14:29:40.871 VRB] <RendererTexture> Alloc Texture #8 ShadowMapArray
[14:29:40.876 VRB] <RendererTexture> Alloc Texture #9 CubeShadowMapArray
[14:29:40.878 ERR] <OpenGL> GL error GL_INVALID_OPERATION
```
Debugger screenshot:
![image](https://user-images.githubusercontent.com/36070899/86511653-d4a53e80-be03-11ea-992e-35a3192149c1.png)

**Comment by arakis** [comment] 2020-07-07 06:48
@LevYas this is a new issue. I moved it #4.

**Comment by LevYas** [comment] 2020-07-07 07:23
Which is interesting, I've just run on Nvidia GT740M and received the same exception:
```
[10:15:46.848 VRB] <Startup`1> 64 Bit System detected. (Pointer Size: 8 Bytes)
[10:15:46.892 VRB] <Startup`1> OS: Microsoft Windows NT 6.2.9200.0
[10:15:46.894 VRB] <Startup`1> Configure for console session
[10:15:46.925 INF] <DebugHelper> Thread #6 Update Thread
[10:15:46.953 INF] <Application> Init Glfw
[10:15:47.024 INF] <Application> GLFW Version: 3.3.0 Win32 WGL EGL OSMesa VisualC DLL
[10:15:47.026 INF] <Application> Create Window
[10:15:48.509 VRB] <RenderWindow> Created window
[10:15:48.555 VRB] <Application> Init OpenGL Bindings
[10:15:48.568 VRB] <Application> Grab Context
[10:15:48.597 VRB] <Application> Load OpenGL Bindings
[10:15:48.609 INF] <Application> Vendor: NVIDIA Corporation, version: 3.3.0 NVIDIA 388.57, shadinglangVersion: 3.30 NVIDIA via Cg compiler, renderer: GeForce GT 740M/PCIe/SSE2
[10:15:48.708 INF] <Texture> Loading: Textures/woodenbox.png
[10:15:48.913 INF] <Texture> Loading: Textures/woodenbox_specular.png
[10:15:48.928 INF] <Texture> Loading: Textures/wood.png
[10:15:49.592 VRB] <RendererTexture> Alloc Texture #1 Color/White
[10:15:49.604 VRB] <RendererTexture> Alloc Texture #2 Color/Black
[10:15:49.605 VRB] <RendererTexture> Alloc Texture #3 Color/Gray
[10:15:49.607 VRB] <RendererTexture> Alloc Texture #4 Color/Red
[10:15:49.608 VRB] <RendererTexture> Alloc Texture #5 Color/Green
[10:15:49.610 VRB] <RendererTexture> Alloc Texture #6 Color/Blue
[10:15:49.619 VRB] <RendererTexture> Alloc Texture #7 Forward
[10:15:49.626 VRB] <RendererTexture> Alloc Texture #8 ShadowMapArray
[10:15:49.631 VRB] <RendererTexture> Alloc Texture #9 CubeShadowMapArray
[10:15:49.635 VRB] <RendererTexture> Alloc Texture #10 GPosition
[10:15:49.637 VRB] <RendererTexture> Alloc Texture #11 GNormal
[10:15:49.640 VRB] <RendererTexture> Alloc Texture #12 GAlbedoSpec
[10:15:49.642 VRB] <RendererTexture> Alloc Texture #13 GMaterial
[10:15:50.033 VRB] <Application> Update Frame #0
[10:15:50.058 VRB] <RendererShader> Compiled shader deferred-shading.vert
[10:15:50.087 VRB] <BindingPoint> Initialized with 32 elements
[10:15:50.090 VRB] <BindingPoint> Allocated Slot 32. Remaining elements: 31
[10:15:50.091 VRB] <Renderer> LightBinding: 32
[10:15:50.260 VRB] <RendererShader> Compiled shader screen.vert
```
```
SixLabors.ImageSharp.ImageProcessingException: 'An error occurred when processing the image using DrawTextProcessor`1.
See the inner exception for more detail.'
Inner Exception: ArgumentOutOfRangeException: Parameter "bufferAlignment" (System.Int32) must be greater than
or equal to 0, was -2147483643 (Parameter 'bufferAlignment')
```

**Comment by arakis** [comment] 2020-07-08 06:51
@LevYas could you please checkout the branch `test/imagesharp-rc3` https://github.com/AximoGames/AxEngine/tree/test/imagesharp-rc3 ? It's just a try with the latest version.

If this still occurs, it would be amazing to track it a little bit more down. Some useful informations:
as I see, "Entry point" of the problem occurs here:
```
var txt = "FPS: " + Math.Round(Application.Current.RenderCounter.EventsPerSecond).ToString();
txt += "\nUPS: " + Math.Round(Application.Current.UpdateCounter.EventsPerSecond).ToString();
Image.Mutate(ctx => ctx.DrawText(txt, DefaultFont, Color.White, new PointF(5, 5)));
```
Could you provide me please the size of Image (width, height), exact txt value, and all properties of DefaultFont (Name, Family, Size).

https://github.com/SixLabors/ImageSharp.Drawing/issues/54 guesses, that the size of the image may zero (but that should be impossible because i give a fixed size of `Vector2i(200, 100)`). The other constructor is not referenced.

**Comment by JimBobSquarePants** [comment] 2020-07-08 07:35
> SixLabors/ImageSharp.Drawing#54 guesses, that the size of the image may zero 

That's not correct. I don't "guess" anything. I've followed the stack trace and I've determined that there are two issues that can cause the exception:

1. That a pen can have a zero width stroke (not relevant in your case).
2. That the outliner calculation can, in some cases return, an empty array which is then causes the `Complex` polygon to create an invalid rectangle which the memory allocation parameters are based upon.

Those issues both need to be fixed so feel free (anyone in this thread) to do so.

**Comment by LevYas** [comment] 2020-07-08 08:02
I've just tried the `test/imagesharp-rc3` branch. Error is still there. 
 txt == "FPS: 0\nUPS: 0" 

![image](https://user-images.githubusercontent.com/36070899/86893401-3cac9b00-c10a-11ea-8a2b-8c05fed5cfea.png)

![image](https://user-images.githubusercontent.com/36070899/86893532-6e256680-c10a-11ea-9ed0-66682b2d7d03.png)

**Comment by JimBobSquarePants** [comment] 2020-07-08 08:19
> I've just tried the test/imagesharp-rc3 branch. Error is still there.

I literally just told you why that would be the case above.

**Comment by arakis** [comment] 2020-07-08 09:07
@JimBobSquarePants 
Ok. We have a valid size (200x100), and a valid font size (12). The Text itself is nothing special and would fit into the image. Maybe it's because of the Font "AcadEref", which seems to be a symbolic font. 

If the AcadEref causes the issue, I see the problem. I just take `SystemFonts.Families.First()` as Font. I never realized that this can result in ugly (and useless) font. On my machine, I do not have any additional fonts installed and got always a good font.

So, i've updated the contructor to `SystemFonts.Families.Find("Arial")`.

What is the preferred way to get a default System Font, Operating system independent, like in CSS `serif `?

@LevYas : Could you please try the latest `test/imagesharp-rc3` branch? Just git pull.

**Comment by LevYas** [comment] 2020-07-09 07:28
Yeaah, it has started successfully :)
![image](https://user-images.githubusercontent.com/36070899/87009923-865eb980-c1ce-11ea-8d86-a4a7537d3029.png)
There are some glitches with shadows though
![image](https://user-images.githubusercontent.com/36070899/87010127-ca51be80-c1ce-11ea-9581-ca1560c8b616.png)
But this could be because of OpenGL ver 3.3. Even the freshest Nvidia drivers did not bring me 4.

**Comment by arakis** [comment] 2020-07-09 11:48
Congratulations, I'm glad to see that this is fixed now. I will merge the patch soonly.

Regarding the shadows: I've opend a new issue at #5

**Closed as completed by arakis** 2020-07-09 11:48 UTC
Labels: bug
