### ISSUE TITLE
Exception while creating shadow cube

### ISSUE THREAD

**Issue by arakis** [arakis/ProcEngine#4] opened 2020-07-07 06:44 UTC
@LevYas wrote in #3 :

I have an exception too, but I'm not sure is the reason the same or not.
After the checkout I run `git-lfs pull` and it downloaded png's.
Console log:
```
[14:29:39.163 VRB] <Startup`1> 64 Bit System detected. (Pointer Size: 8 Bytes)
[14:29:39.204 VRB] <Startup`1> OS: Microsoft Windows NT 6.2.9200.0
[14:29:39.207 VRB] <Startup`1> Configure for console session
[14:29:39.237 INF] <DebugHelper> Thread #6 Update Thread
[14:29:39.265 INF] <Application> Init Glfw
[14:29:39.361 INF] <Application> GLFW Version: 3.3.0 Win32 WGL EGL OSMesa VisualC DLL
[14:29:39.363 INF] <Application> Create Window
[14:29:39.556 VRB] <RenderWindow> Created window
[14:29:39.575 VRB] <Application> Init OpenGL Bindings
[14:29:39.577 VRB] <Application> Grab Context
[14:29:39.580 VRB] <Application> Load OpenGL Bindings
[14:29:39.582 INF] <Application> Vendor: Intel, version: 3.3.0 - Build 10.18.10.5059, shadinglangVersion: 3.30 - Build 10.18.10.5059, renderer: Intel(R) HD Graphics 4000
[14:29:39.659 INF] <Texture> Loading: Textures/woodenbox.png
[14:29:39.847 INF] <Texture> Loading: Textures/woodenbox_specular.png
[14:29:39.866 INF] <Texture> Loading: Textures/wood.png
[14:29:40.835 VRB] <Application> Update Frame #0
[14:29:40.841 VRB] <RendererTexture> Alloc Texture #1 Color/White
[14:29:40.852 VRB] <RendererTexture> Alloc Texture #2 Color/Black
[14:29:40.854 VRB] <RendererTexture> Alloc Texture #3 Color/Gray
[14:29:40.856 VRB] <RendererTexture> Alloc Texture #4 Color/Red
[14:29:40.857 VRB] <RendererTexture> Alloc Texture #5 Color/Green
[14:29:40.859 VRB] <RendererTexture> Alloc Texture #6 Color/Blue
[14:29:40.866 VRB] <RendererTexture> Alloc Texture #7 Forward
[14:29:40.871 VRB] <RendererTexture> Alloc Texture #8 ShadowMapArray
[14:29:40.876 VRB] <RendererTexture> Alloc Texture #9 CubeShadowMapArray
[14:29:40.878 ERR] <OpenGL> GL error GL_INVALID_OPERATION
```
Debugger screenshot:
![image](https://user-images.githubusercontent.com/36070899/86511653-d4a53e80-be03-11ea-992e-35a3192149c1.png)

_Originally posted by @LevYas in https://github.com/AximoGames/AxEngine/issues/3#issuecomment-653754972_

**Comment by arakis** [comment] 2020-07-07 06:53
@LevYas
As I see, you have "shadinglangVersion: 3.30, Intel(R) HD Graphics 4000". This means you do not have OpenGL4. Currently, OpenGL below V4 is not supported.

**Comment by LevYas** [comment] 2020-07-07 07:21
Which is interesting, I've just run on Nvidia GT740M (But OpenGL is still 3) and received the same exception as in the original post:
```
[10:15:46.848 VRB] <Startup`1> 64 Bit System detected. (Pointer Size: 8 Bytes)
[10:15:46.892 VRB] <Startup`1> OS: Microsoft Windows NT 6.2.9200.0
[10:15:46.894 VRB] <Startup`1> Configure for console session
[10:15:46.925 INF] <DebugHelper> Thread #6 Update Thread
[10:15:46.953 INF] <Application> Init Glfw
[10:15:47.024 INF] <Application> GLFW Version: 3.3.0 Win32 WGL EGL OSMesa VisualC DLL
[10:15:47.026 INF] <Application> Create Window
[10:15:48.509 VRB] <RenderWindow> Created window
[10:15:48.555 VRB] <Application> Init OpenGL Bindings
[10:15:48.568 VRB] <Application> Grab Context
[10:15:48.597 VRB] <Application> Load OpenGL Bindings
[10:15:48.609 INF] <Application> Vendor: NVIDIA Corporation, version: 3.3.0 NVIDIA 388.57, shadinglangVersion: 3.30 NVIDIA via Cg compiler, renderer: GeForce GT 740M/PCIe/SSE2
[10:15:48.708 INF] <Texture> Loading: Textures/woodenbox.png
[10:15:48.913 INF] <Texture> Loading: Textures/woodenbox_specular.png
[10:15:48.928 INF] <Texture> Loading: Textures/wood.png
[10:15:49.592 VRB] <RendererTexture> Alloc Texture #1 Color/White
[10:15:49.604 VRB] <RendererTexture> Alloc Texture #2 Color/Black
[10:15:49.605 VRB] <RendererTexture> Alloc Texture #3 Color/Gray
[10:15:49.607 VRB] <RendererTexture> Alloc Texture #4 Color/Red
[10:15:49.608 VRB] <RendererTexture> Alloc Texture #5 Color/Green
[10:15:49.610 VRB] <RendererTexture> Alloc Texture #6 Color/Blue
[10:15:49.619 VRB] <RendererTexture> Alloc Texture #7 Forward
[10:15:49.626 VRB] <RendererTexture> Alloc Texture #8 ShadowMapArray
[10:15:49.631 VRB] <RendererTexture> Alloc Texture #9 CubeShadowMapArray
[10:15:49.635 VRB] <RendererTexture> Alloc Texture #10 GPosition
[10:15:49.637 VRB] <RendererTexture> Alloc Texture #11 GNormal
[10:15:49.640 VRB] <RendererTexture> Alloc Texture #12 GAlbedoSpec
[10:15:49.642 VRB] <RendererTexture> Alloc Texture #13 GMaterial
[10:15:50.033 VRB] <Application> Update Frame #0
[10:15:50.058 VRB] <RendererShader> Compiled shader deferred-shading.vert
[10:15:50.087 VRB] <BindingPoint> Initialized with 32 elements
[10:15:50.090 VRB] <BindingPoint> Allocated Slot 32. Remaining elements: 31
[10:15:50.091 VRB] <Renderer> LightBinding: 32
[10:15:50.260 VRB] <RendererShader> Compiled shader screen.vert
```
I'll post it there too

**Comment by LevYas** [comment] 2020-07-07 07:25
If you're not intended to support older OpenGL, I think we can close this issue.

**Closed as completed** 2020-07-08 09:16 UTC
Labels: bug, wontfix

**Comment by LevYas** [comment] 2020-07-08 10:56
BTW, this issue is not reproducible after updating the HD 4000 driver to the latest version. GL is still 3rd though.
